-- MarketPulse canonical Supabase schema notice
-- Production project: iqavukfmeahqnovrkcuo
-- Do not restore the original AI Studio prototype SQL.
-- Canonical tables: profiles, agents, categories, brands, pack_sizes, products,
-- product_aliases, markets, stores_vendors, price_observations, evidence_photos,
-- confidence_scores, verification_records, reports, audit_logs,
-- published_city_prices, published_market_prices, published_price_history_daily,
-- saved_products, client_error_events, privacy_requests, recovery_drills,
-- pilot_readiness_snapshots.
-- Every signup starts public_user. Super admin alone appoints field_agent/verifier_admin.
-- Public prices are derived only from approved city/market observations; products do not hold a global current price.
-- Field evidence is private; profile avatars are public identity assets.
-- Operational migrations in this repository are additive to the already-provisioned core production schema.
