export type UserRole = 'consumer' | 'agent' | 'admin' | 'super_admin';
export type ThemeMode = 'light' | 'dark' | 'system';
export type ProductCategory = 'Food Staples' | 'Fresh Food' | 'Meat & Seafood' | 'Household' | 'Personal Care' | 'Beverages';
export type ConfidenceLevel = 'High Confidence' | 'Moderate Confidence' | 'Limited Data' | 'Stale';
export interface Market { id:string; name:string; city:string; state:string; address:string; image:string; healthScore:number; confidenceScore:number; productsCount:number; updatesToday:number; lastUpdated:string; coordinates:{lat:number;lng:number}; openingHours:string; description:string; isActive:boolean; }
export interface MarketPrice { marketId:string; marketName:string; city:string; state:string; price:number; lowPrice?:number; highPrice?:number; observationCount?:number; confidenceScore?:number; isLowest?:boolean; lastVerified:string; }
export interface PriceTrendPoint { date:string; price:number; avgPrice:number; lowPrice?:number; highPrice?:number; observationCount?:number; }
export interface Product { id:string; name:string; brand?:string; category:ProductCategory; categorySlug:string; image:string; unit:string; unitWeight?:string; isLocalOrImported?:'Local'|'Imported'|'Both'; sizeOption?:string; aliases:string[]; currentAvgPrice:number; priceChangePercent:number; priceChangeDirection:'up'|'down'|'neutral'; priceLow:number; priceHigh:number; lastVerified:string; lastVerifiedAt:string|null; confidence:ConfidenceLevel; confidenceScore:number; observationsCount:number; marketsCount:number; insight:string; hasVerifiedPrice:boolean; marketPrices:MarketPrice[]; priceTrends:{today:PriceTrendPoint[];'7D':PriceTrendPoint[];'30D':PriceTrendPoint[];'3M':PriceTrendPoint[]}; }
export interface FieldSubmission { id:string; submissionNumber:string; productId:string; productName:string; marketId:string; marketName:string; city:string; price:number; quantity:number; unit:string; sellerStall:string; agentId:string; agentName:string; agentInitials:string; agentLevel:string; agentReputation:number; photoUrl:string|null; evidenceStoragePath:string|null; exifMatched:boolean|null; gpsLocation:{lat:number;lng:number;accuracyMeters:number|null;distanceToMarketMeters:number|null;address:string}; submittedAt:string; timestamp:string; capturedAt:string; status:'pending'|'verified'|'flagged'|'rejected'|'recheck_requested'; systemConfidence:number; systemRecommendation:'Likely Valid'|'Potential Anomaly'|'Needs Recheck'; anomalyNote?:string; isOfflineQueued?:boolean; nearbyMarketComparisons:Array<{marketName:string;price:number;verified:boolean}>; }
export interface AgentProfile { id:string; name:string; email:string; avatar:string; agentCode:string; tier:'Trusted Agent'|'Senior Agent'|'Field Agent'; accuracyRate:number; totalSubmissions:number; verifiedSubmissions:number; rejectedSubmissions:number; pendingVerificationsCount:number; completedChecksToday:number; assignedMarkets:Array<{id:string;name:string;city:string}>; isFieldActive:boolean; }
export interface AdminKPIs { verifiedToday:number; verifiedGrowthPercent:number; pendingVerification:number; activeAgents:number; regionsCovered:number; averageFreshnessMinutes:number; freshnessImprovementMinutes:number; systemConfidenceScore:number; }
export interface SystemAlert { id:string; type:'error'|'warning'|'info'; title?:string; message:string; timestamp?:string; count?:number; }
export interface SavedItem { productId:string; savedAt:string; targetPriceAlert?:number; notifyOnVolatility?:boolean; }
export interface AuditLogEntry { id:string; timestamp:string; actorId:string; actorName:string; actorRole:string; action:string; entityType:'submission'|'product'|'market'|'agent'|'system'|'profile'; entityId:string; entityName:string; marketName?:string; city?:string; status:'SUCCESS'|'WARNING'|'ALERT'|'INFO'; details:string; confidenceScore?:number; price?:number; }
export interface DeviceLocation { lat:number; lng:number; accuracyMeters:number|null; capturedAt:string; }
