import React, { useMemo, useState } from 'react';
import { ArrowLeft, Clock3, MapPin, Search, Store } from 'lucide-react';
import { useApp } from '../context/AppContext';
export const DiscoverMarketsView:React.FC=()=>{
 const {markets,selectedCity,openMarketDetail,setActiveView}=useApp(); const [q,setQ]=useState('');
 const rows=useMemo(()=>markets.filter(m=>m.city===selectedCity&&(`${m.name} ${m.address}`.toLowerCase().includes(q.toLowerCase()))),[markets,selectedCity,q]);
 const tracked=rows.reduce((s,m)=>s+m.productsCount,0), updates=rows.reduce((s,m)=>s+m.updatesToday,0);
 return <div className="space-y-5 pb-20"><div className="flex gap-3 items-center"><button onClick={()=>setActiveView('home')} className="p-2 rounded-full hover:bg-[#eff4ff]"><ArrowLeft className="w-5 h-5"/></button><div><h1 className="text-2xl font-bold">Markets in {selectedCity}</h1><p className="text-xs text-[#6e7a70]">Coverage and freshness come from approved price observations.</p></div></div>
 <div className="grid sm:grid-cols-3 gap-3"><S label="Active markets" value={rows.filter(m=>m.isActive).length}/><S label="Products with market data" value={tracked}/><S label="Market-price updates today" value={updates}/></div>
 <div className="flex items-center gap-2 bg-white dark:bg-[#182232] border border-[#bdcabe]/40 dark:border-[#2d3e58] rounded-2xl px-4"><Search className="w-4 h-4 text-[#6e7a70]"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search markets…" className="flex-1 bg-transparent py-3 text-sm focus:outline-none"/></div>
 <div className="grid md:grid-cols-2 gap-4">{rows.map(m=><button key={m.id} onClick={()=>openMarketDetail(m)} className="text-left bg-white dark:bg-[#182232] border border-[#bdcabe]/40 dark:border-[#2d3e58] rounded-2xl overflow-hidden hover:border-[#008751]"><img src={m.image} alt="" className="w-full h-40 object-cover bg-[#eef6f1]"/><div className="p-4"><div className="flex justify-between gap-3"><div><h2 className="font-bold">{m.name}</h2><p className="text-xs text-[#6e7a70] mt-1 flex items-center gap-1"><MapPin className="w-3 h-3"/>{m.address}</p></div><span className="text-[10px] px-2 py-1 h-fit rounded-full bg-emerald-100 text-emerald-700 font-bold">{m.isActive?'Active':'Inactive'}</span></div><div className="grid grid-cols-3 gap-2 mt-4 text-center"><Mini label="Products" value={m.productsCount}/><Mini label="Today" value={m.updatesToday}/><Mini label="Confidence" value={m.confidenceScore?`${m.confidenceScore}%`:'—'}/></div><p className="text-[11px] text-[#6e7a70] mt-3 flex items-center gap-1"><Clock3 className="w-3 h-3"/>{m.openingHours} · Data {m.lastUpdated}</p></div></button>)}</div>
 {!rows.length&&<div className="py-14 text-center text-sm text-[#6e7a70]"><Store className="w-8 h-8 mx-auto mb-2"/>No markets match this search.</div>}</div>;
};
const S:React.FC<{label:string;value:string|number}>=({label,value})=><div className="rounded-2xl bg-white dark:bg-[#182232] border border-[#bdcabe]/40 dark:border-[#2d3e58] p-4"><p className="text-2xl font-bold">{value}</p><p className="text-xs text-[#6e7a70]">{label}</p></div>;
const Mini=S;
