import React, { useMemo, useState } from 'react';
import { Bookmark, CheckCircle2, Flag, MapPin, ShieldCheck, TrendingDown, TrendingUp, X } from 'lucide-react';
import { useApp } from '../context/AppContext';

export const ProductDetailModal: React.FC = () => {
  const { selectedProduct:p, closeProductDetail, isProductSaved, toggleSaveProduct, openReportModal, selectedCity } = useApp();
  const [timeframe,setTimeframe]=useState<'today'|'7D'|'30D'|'3M'>('30D');
  const points=useMemo(()=>p?.priceTrends[timeframe]||[],[p,timeframe]);
  if(!p) return null;
  return <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm overflow-y-auto p-3 sm:p-6">
    <div className="max-w-4xl mx-auto bg-white dark:bg-[#182232] rounded-3xl border border-[#bdcabe]/40 dark:border-[#2d3e58] shadow-2xl overflow-hidden">
      <div className="p-5 sm:p-6 border-b border-[#bdcabe]/30 dark:border-[#2d3e58] flex gap-4">
        <img src={p.image} alt="" className="w-20 h-20 rounded-2xl object-cover bg-[#eef6f1]"/><div className="flex-1 min-w-0"><p className="text-xs text-[#6e7a70]">{p.category} · {p.brand||'Unbranded'}</p><h2 className="text-xl sm:text-2xl font-bold mt-1">{p.name}</h2><p className="text-xs text-[#6e7a70] mt-1">Canonical unit: {p.unit} · {selectedCity}</p></div><button onClick={closeProductDetail} className="p-2 h-fit rounded-full hover:bg-[#eff4ff] dark:hover:bg-[#25344a]"><X className="w-5 h-5"/></button>
      </div>
      <div className="p-5 sm:p-6 space-y-6">
        {p.hasVerifiedPrice ? <>
          <section className="grid md:grid-cols-3 gap-4"><div className="md:col-span-2 rounded-2xl bg-[#f5fbf7] dark:bg-[#121c2a] border border-[#008751]/20 p-5"><p className="text-xs font-bold uppercase tracking-wide text-[#6e7a70]">Current verified city average</p><div className="flex items-end gap-3 mt-2"><p className="text-4xl font-bold">₦{p.currentAvgPrice.toLocaleString()}</p>{p.priceChangeDirection!=='neutral'&&<span className={`text-xs font-bold flex items-center gap-1 ${p.priceChangeDirection==='up'?'text-rose-600':'text-emerald-600'}`}>{p.priceChangeDirection==='up'?<TrendingUp className="w-4 h-4"/>:<TrendingDown className="w-4 h-4"/>}{Math.abs(p.priceChangePercent).toFixed(1)}%</span>}</div><p className="text-sm mt-2 text-[#6e7a70]">Range ₦{p.priceLow.toLocaleString()}–₦{p.priceHigh.toLocaleString()} · last verified {p.lastVerified}</p></div><div className="rounded-2xl border border-[#bdcabe]/40 dark:border-[#2d3e58] p-5"><div className="flex items-center gap-2 text-[#008751]"><ShieldCheck className="w-5 h-5"/><p className="font-bold">{p.confidence}</p></div><p className="text-3xl font-bold mt-2">{Math.round(p.confidenceScore)}%</p><p className="text-xs text-[#6e7a70] mt-2">{p.observationsCount} approved observation{p.observationsCount===1?'':'s'} across {p.marketsCount} market{p.marketsCount===1?'':'s'}.</p></div></section>
          <section className="rounded-2xl border border-[#bdcabe]/40 dark:border-[#2d3e58] p-5"><h3 className="font-bold">Why this price is trustworthy</h3><div className="grid sm:grid-cols-3 gap-3 mt-4"><Trust text={`${p.observationsCount} approved observations`}/><Trust text={`${p.marketsCount} market${p.marketsCount===1?'':'s'} represented`}/><Trust text={`Freshness: ${p.lastVerified}`}/></div><p className="text-xs text-[#6e7a70] mt-4">Confidence is calculated from actual approved observations, freshness, market diversity and server-side quality signals. MarketPulse does not claim EXIF or GPS validation publicly unless those signals were actually evaluated.</p></section>
          <section><div className="flex justify-between items-end"><div><h3 className="font-bold">Prices by market</h3><p className="text-xs text-[#6e7a70]">Approved aggregates only</p></div></div><div className="mt-3 space-y-2">{p.marketPrices.length?p.marketPrices.map(mp=><div key={mp.marketId} className="p-4 rounded-xl bg-[#f8f9ff] dark:bg-[#121c2a] border border-[#bdcabe]/30 dark:border-[#2d3e58] flex justify-between gap-3"><div><p className="font-bold text-sm flex items-center gap-1"><MapPin className="w-3.5 h-3.5 text-[#008751]"/>{mp.marketName}</p><p className="text-[11px] text-[#6e7a70] mt-1">{mp.observationCount||0} observations · {mp.lastVerified}</p></div><div className="text-right"><p className="font-bold">₦{mp.price.toLocaleString()}</p>{mp.isLowest&&<p className="text-[10px] font-bold text-emerald-600">Lowest verified average</p>}</div></div>):<p className="text-xs text-[#6e7a70] py-6">No market-level aggregates are available yet.</p>}</div></section>
          <section className="rounded-2xl border border-[#bdcabe]/40 dark:border-[#2d3e58] p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold">Price history</h3><p className="text-xs text-[#6e7a70]">Real approved daily aggregates; no synthetic chart points.</p></div><div className="flex gap-1">{(['today','7D','30D','3M'] as const).map(t=><button key={t} onClick={()=>setTimeframe(t)} className={`px-3 py-1.5 rounded-full text-[11px] font-bold ${timeframe===t?'bg-[#008751] text-white':'bg-[#eff4ff] dark:bg-[#25344a]'}`}>{t}</button>)}</div></div>{points.length?<div className="mt-5 flex items-end gap-1 h-32 border-b border-[#bdcabe]/40">{points.map((pt,i)=>{const vals=points.map(x=>x.price);const min=Math.min(...vals),max=Math.max(...vals);const h=max===min?55:20+((pt.price-min)/(max-min))*80;return <div key={`${pt.date}-${i}`} title={`${pt.date}: ₦${pt.price.toLocaleString()}`} className="flex-1 bg-[#008751]/70 rounded-t" style={{height:`${h}%`}}/>})}</div>:<div className="py-10 text-center text-xs text-[#6e7a70]">Not enough verified history for this period yet.</div>}</section>
        </> : <section className="py-12 text-center rounded-2xl border border-dashed border-[#bdcabe]"><ShieldCheck className="w-10 h-10 text-[#008751] mx-auto"/><h3 className="font-bold text-lg mt-3">No verified price published yet</h3><p className="max-w-lg mx-auto text-sm text-[#6e7a70] mt-2">This product is in the catalog, but MarketPulse will not display a “current price” until field observations have been reviewed and approved.</p></section>}
        <div className="flex flex-wrap gap-2"><button onClick={()=>void toggleSaveProduct(p.id)} className="px-4 py-2.5 rounded-xl border border-[#bdcabe]/50 text-xs font-bold flex items-center gap-2"><Bookmark className={`w-4 h-4 ${isProductSaved(p.id)?'fill-current text-[#008751]':''}`}/>{isProductSaved(p.id)?'Saved':'Save product'}</button>{p.hasVerifiedPrice&&p.marketPrices.length>0&&<button onClick={()=>{closeProductDetail();openReportModal(p)}} className="px-4 py-2.5 rounded-xl border border-rose-200 text-rose-600 text-xs font-bold flex items-center gap-2"><Flag className="w-4 h-4"/>Report inaccurate price</button>}</div>
      </div>
    </div>
  </div>;
};
const Trust:React.FC<{text:string}>=({text})=><div className="flex gap-2 items-center rounded-xl bg-[#f8f9ff] dark:bg-[#121c2a] p-3 text-xs"><CheckCircle2 className="w-4 h-4 text-[#008751] shrink-0"/>{text}</div>;
