import React, { useMemo } from 'react';
import { ArrowLeft, Search, ShieldCheck } from 'lucide-react';
import { useApp } from '../context/AppContext';

export const SearchResults: React.FC = () => {
  const { products, searchQuery, setSearchQuery, selectedCategory, setSelectedCategory, selectedOriginFilter, setSelectedOriginFilter, selectedSort, setSelectedSort, setActiveView, openProductDetail, selectedCity } = useApp();
  const results = useMemo(()=>{
    const q=searchQuery.trim().toLowerCase();
    const rows=products.filter(p => (!q || `${p.name} ${p.brand||''} ${p.category} ${p.aliases.join(' ')}`.toLowerCase().includes(q)) && (selectedCategory==='All'||p.category===selectedCategory) && (selectedOriginFilter==='All'||p.isLocalOrImported===selectedOriginFilter||p.isLocalOrImported==='Both'));
    return [...rows].sort((a,b)=> selectedSort==='price_asc' ? (a.hasVerifiedPrice? a.currentAvgPrice:Number.MAX_SAFE_INTEGER)-(b.hasVerifiedPrice?b.currentAvgPrice:Number.MAX_SAFE_INTEGER) : selectedSort==='price_desc' ? b.currentAvgPrice-a.currentAvgPrice : selectedSort==='recent' ? new Date(b.lastVerifiedAt||0).getTime()-new Date(a.lastVerifiedAt||0).getTime() : b.confidenceScore-a.confidenceScore);
  },[products,searchQuery,selectedCategory,selectedOriginFilter,selectedSort]);
  return <div className="space-y-5 pb-20">
    <div className="flex gap-3 items-center"><button onClick={()=>setActiveView('home')} className="p-2 rounded-full hover:bg-[#eff4ff]"><ArrowLeft className="w-5 h-5"/></button><div><h1 className="text-2xl font-bold">Search prices</h1><p className="text-xs text-[#6e7a70]">{selectedCity} verified catalog</p></div></div>
    <div className="bg-white dark:bg-[#182232] border border-[#bdcabe]/50 dark:border-[#2d3e58] rounded-2xl p-3 flex gap-2 items-center"><Search className="w-4 h-4 text-[#6e7a70]"/><input autoFocus value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} placeholder="Try ‘red oil’, ‘tissue’, ‘Maggi’…" className="flex-1 bg-transparent py-2 text-sm focus:outline-none"/></div>
    <div className="flex flex-wrap gap-2"><select value={selectedCategory} onChange={e=>setSelectedCategory(e.target.value as any)} className="rounded-full border border-[#bdcabe]/50 dark:border-[#2d3e58] bg-white dark:bg-[#182232] px-3 py-2 text-xs"><option>All</option><option>Food Staples</option><option>Fresh Food</option><option>Meat & Seafood</option><option>Household</option><option>Personal Care</option><option>Beverages</option></select><select value={selectedOriginFilter} onChange={e=>setSelectedOriginFilter(e.target.value as any)} className="rounded-full border border-[#bdcabe]/50 dark:border-[#2d3e58] bg-white dark:bg-[#182232] px-3 py-2 text-xs"><option>All</option><option>Local</option><option>Imported</option></select><select value={selectedSort} onChange={e=>setSelectedSort(e.target.value as any)} className="rounded-full border border-[#bdcabe]/50 dark:border-[#2d3e58] bg-white dark:bg-[#182232] px-3 py-2 text-xs"><option value="confidence">Best confidence</option><option value="recent">Most recent</option><option value="price_asc">Price low-high</option><option value="price_desc">Price high-low</option></select></div>
    <p className="text-xs text-[#6e7a70]">{results.length} matching product{results.length===1?'':'s'}. Aliases and common Nigerian market terms are searchable.</p>
    <div className="space-y-3">{results.map(p=><button key={p.id} onClick={()=>openProductDetail(p)} className="w-full text-left bg-white dark:bg-[#182232] border border-[#bdcabe]/40 dark:border-[#2d3e58] rounded-2xl p-4 flex gap-4 hover:border-[#008751]"><img src={p.image} alt="" className="w-20 h-20 rounded-xl object-cover"/><div className="flex-1 min-w-0"><div className="flex justify-between gap-3"><div><p className="font-bold truncate">{p.name}</p><p className="text-xs text-[#6e7a70]">{p.brand||'Unbranded'} · {p.unit}</p></div>{p.hasVerifiedPrice&&<span className="text-[10px] h-fit px-2 py-1 rounded-full bg-emerald-100 text-emerald-700 font-bold flex items-center gap-1"><ShieldCheck className="w-3 h-3"/>{p.confidenceScore}%</span>}</div>{p.hasVerifiedPrice?<><p className="text-xl font-bold mt-2">₦{p.currentAvgPrice.toLocaleString()}</p><p className="text-[11px] text-[#6e7a70]">Low ₦{p.priceLow.toLocaleString()} · High ₦{p.priceHigh.toLocaleString()} · {p.lastVerified}</p></>:<div className="mt-3 text-xs font-semibold text-[#6e7a70]">Awaiting approved field observations</div>}</div></button>)}</div>
    {!results.length&&<div className="py-14 text-center text-sm text-[#6e7a70]">No catalog match. Try a broader product name or common alias.</div>}
  </div>;
};
